name: Publish Documentation

on:
  # Trigger when documentation files change
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'target/documentation/**'
      - '.github/workflows/publish-docs.yml'
  
  # Allow manual triggering
  workflow_dispatch:

# Allow workflow to write to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc
    
    - name: Create documentation site
      run: ./.github/workflows/generate-docs.sh
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./pages
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    
    - name: Output deployment URL
      run: |
        echo "📖 Documentation deployed to: ${{ steps.deployment.outputs.page_url }}"